from __future__ import annotations
"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    Config, Conveyor, ErrorHandling, Feedback, Io, Lifecycle, Motion,
    Modbus, Query, Raw, RelativeMotion, System, Welding, ForceControl
)
from ..exceptions import NotSupportedError

if TYPE_CHECKING:
    import numpy as np
    from ..types import Pose


# ============================================================================
# V4 NAMESPACE IMPLEMENTATIONS
# ============================================================================



def _opt(val: int | None) -> int:
    # helper for converting None to -1 in options
    return val if val is not None else -1


def _pose_from_v4(v4_pose: V4Pose) -> Pose:
    """Convert a V4 ``dobot_api_v4.Pose`` to our unified :class:`Pose`."""
    return Pose(
        x=v4_pose.x,
        y=v4_pose.y,
        z=v4_pose.z,
        rx=v4_pose.rx,
        ry=v4_pose.ry,
        rz=v4_pose.rz,
    )




class ForceControlV4(ForceControl):
    """Concrete ForceControl implementation for V4 API."""

    def enable_ft_sensor(self, status: int) -> None:
        """Enable or disable the force/torque sensor."""
        self.native.dashboard.enable_ft_sensor(status)

    def fc_off(self) -> None:
        """Turn off force-compliance mode."""
        self.native.fc_off()

    def get_force(self) -> Pose:
        """Return force/torque readings from the sensor."""
        return _pose_from_v4(self.native.get_force())

    def six_force_home(self) -> None:
        """Zero (home) the six-axis force/torque sensor."""
        self.native.dashboard.six_force_home()
