from __future__ import annotations

"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    Io,
)

if TYPE_CHECKING:
    from ..types import Pose


# ============================================================================
# V4 NAMESPACE IMPLEMENTATIONS
# ============================================================================


def _opt(val: int | None) -> int:
    # helper for converting None to -1 in options
    return val if val is not None else -1


def _pose_from_v4(v4_pose: V4Pose) -> Pose:
    """Convert a V4 ``dobot_api_v4.Pose`` to our unified :class:`Pose`."""
    return Pose(
        x=v4_pose.x,
        y=v4_pose.y,
        z=v4_pose.z,
        rx=v4_pose.rx,
        ry=v4_pose.ry,
        rz=v4_pose.rz,
    )


class IoV4(Io):
    """Concrete Io implementation for V4 API."""

    def ai(self, index: int) -> int:
        """Read an analogue input."""
        return self.native.dashboard.ai(index)

    def ao(self, index: int, value: float) -> None:
        """Set an analogue output."""
        self.native.ao(index, value)

    def ao_instant(self, index: int, value: float) -> None:
        """Set an analogue output immediately."""
        self.native.dashboard.ao_instant(index, value)

    def di(self, index: int) -> int:
        """Read a digital input."""
        return self.native.di(index)

    def do_instant(self, index: int, status: int) -> None:
        """Set a digital output immediately (bypasses the motion queue)."""
        self.native.dashboard.do_instant(index, status)

    def do_output(self, index: int, status: int) -> None:
        """Set a digital output."""
        self.native.do_output(index, status)

    def get_ao(self, index: int) -> float:
        """Read the current value of an analogue output."""
        return float(self.native.dashboard.get_ao(index))

    def get_do(self, index: int) -> int:
        """Read the current status of a digital output."""
        return self.native.get_do(index)

    def get_tool_do(self, index: int) -> int:
        """Read the current status of a tool digital output."""
        return self.native.dashboard.get_tool_do(index)

    def tool_ai(self, index: int) -> int:
        """Read a tool analogue input."""
        return self.native.dashboard.tool_ai(index)

    def tool_di(self, index: int) -> int:
        """Read a tool digital input."""
        return self.native.dashboard.tool_di(index)

    def tool_do(self, index: int, status: int) -> None:
        """Set a tool digital output."""
        self.native.dashboard.tool_do(index, status)

    def tool_do_instant(self, index: int, status: int) -> None:
        """Set a tool digital output immediately."""
        self.native.dashboard.tool_do_instant(index, status)
