from __future__ import annotations
"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    Config, Conveyor, ErrorHandling, Feedback, Io, Lifecycle, Motion,
    Modbus, Query, Raw, RelativeMotion, System, Welding, ForceControl
)
from ..exceptions import NotSupportedError

if TYPE_CHECKING:
    import numpy as np
    from ..types import Pose


# ============================================================================
# V4 NAMESPACE IMPLEMENTATIONS
# ============================================================================



def _opt(val: int | None) -> int:
    # helper for converting None to -1 in options
    return val if val is not None else -1


def _pose_from_v4(v4_pose: V4Pose) -> Pose:
    """Convert a V4 ``dobot_api_v4.Pose`` to our unified :class:`Pose`."""
    return Pose(
        x=v4_pose.x,
        y=v4_pose.y,
        z=v4_pose.z,
        rx=v4_pose.rx,
        ry=v4_pose.ry,
        rz=v4_pose.rz,
    )




class LifecycleV4(Lifecycle):
    """Concrete Lifecycle implementation for V4 API."""

    def disconnect(self) -> None:
        """Close all TCP connections."""
        if self.native is not None:
            self.native.close()
            self.native = None  # type: ignore[assignment]

    def reconnect(self) -> None:
        """Re-establish all TCP connections."""
        self.native.reconnect()

    def shutdown(self) -> None:
        """Gracefully disable the robot arm."""
        logger.info("V4 shutdown: disabling robot")
        self.native.disable_robot()

    def startup(
        self,
        speed: int = 40,
        load: float = 0.0,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
        *,
        power_on_wait: float = 15.0,
    ) -> None:
        """V4 startup — composed manually since there's no built-in startup()."""
        logger.info("V4 startup sequence starting")
        has_errors = self.native.check_errors(language=self._language)
        if has_errors:
            logger.info("Errors detected — clearing and powering on")
            self.native.clear_error()
            self.native.power_on()
            logger.info(f"Waiting {power_on_wait}s for controller to power on")
            time.sleep(power_on_wait)
        else:
            logger.info("No errors detected — skipping clear_error and power_on")
        self.native.disable_robot()
        self.native.enable_robot(
            load=load,
            center_x=center_x,
            center_y=center_y,
            center_z=center_z,
        )
        self.native.speed_factor(speed)
        logger.info("V4 startup sequence complete")
