from __future__ import annotations
"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    Config, Conveyor, ErrorHandling, Feedback, Io, Lifecycle, Motion,
    Modbus, Query, Raw, RelativeMotion, System, Welding, ForceControl
)
from ..exceptions import NotSupportedError

if TYPE_CHECKING:
    import numpy as np
    from ..types import Pose


# ============================================================================
# V4 NAMESPACE IMPLEMENTATIONS
# ============================================================================



def _opt(val: int | None) -> int:
    # helper for converting None to -1 in options
    return val if val is not None else -1


def _pose_from_v4(v4_pose: V4Pose) -> Pose:
    """Convert a V4 ``dobot_api_v4.Pose`` to our unified :class:`Pose`."""
    return Pose(
        x=v4_pose.x,
        y=v4_pose.y,
        z=v4_pose.z,
        rx=v4_pose.rx,
        ry=v4_pose.ry,
        rz=v4_pose.rz,
    )




class ModbusV4(Modbus):
    """Concrete Modbus implementation for V4 API."""

    def get_hold_regs(self, index: int, addr: int, count: int, val_type: str = "") -> list | int | float:
        return self.native.get_hold_regs(index, addr, count, val_type)

    def modbus_close(self, index: int) -> None:
        self.native.modbus_close(index)

    def modbus_create(self, ip: str, port: int, slave_id: int, is_rtu: int = -1) -> int:
        return self.native.modbus_create(ip, port, slave_id, is_rtu)

    def set_hold_regs(self, index: int, addr: int, count: int, val_tab: str | list, val_type: str = "") -> None:
        self.native.set_hold_regs(index, addr, count, val_tab, val_type)
