from __future__ import annotations
"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    Config, Conveyor, ErrorHandling, Feedback, Io, Lifecycle, Motion,
    Modbus, Query, Raw, RelativeMotion, System, Welding, ForceControl
)
from ..exceptions import NotSupportedError

if TYPE_CHECKING:
    import numpy as np
    from ..types import Pose


# ============================================================================
# V4 NAMESPACE IMPLEMENTATIONS
# ============================================================================



def _opt(val: int | None) -> int:
    # helper for converting None to -1 in options
    return val if val is not None else -1


def _pose_from_v4(v4_pose: V4Pose) -> Pose:
    """Convert a V4 ``dobot_api_v4.Pose`` to our unified :class:`Pose`."""
    return Pose(
        x=v4_pose.x,
        y=v4_pose.y,
        z=v4_pose.z,
        rx=v4_pose.rx,
        ry=v4_pose.ry,
        rz=v4_pose.rz,
    )




class RawV4(Raw):
    """Concrete Raw implementation for V4 API."""

    def send_raw(self, command: str) -> str:
        """Send a raw TCP command string and return the raw response."""
        return self.native.dashboard.send_recv_msg(command)
