from __future__ import annotations

"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    RelativeMotion,
)

if TYPE_CHECKING:
    from ..types import Pose


# ============================================================================
# V4 NAMESPACE IMPLEMENTATIONS
# ============================================================================


def _opt(val: int | None) -> int:
    # helper for converting None to -1 in options
    return val if val is not None else -1


def _pose_from_v4(v4_pose: V4Pose) -> Pose:
    """Convert a V4 ``dobot_api_v4.Pose`` to our unified :class:`Pose`."""
    return Pose(
        x=v4_pose.x,
        y=v4_pose.y,
        z=v4_pose.z,
        rx=v4_pose.rx,
        ry=v4_pose.ry,
        rz=v4_pose.rz,
    )


class RelativeMotionV4(RelativeMotion):
    """Concrete RelativeMotion implementation for V4 API."""

    def rel_joint_mov_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative move with joint offsets."""
        return self.native.dashboard.rel_joint_mov_j(
            j1,
            j2,
            j3,
            j4,
            j5,
            j6,
            a=_opt(accel),
            v=_opt(speed),
        )

    def rel_mov_j_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        tool: int | None = None,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative joint move in tool coordinate system."""
        return self.native.dashboard.rel_mov_j_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user=_opt(user),
            tool=_opt(tool),
            a=_opt(accel),
            v=_opt(speed),
        )

    def rel_mov_j_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative joint move in user coordinate system."""
        return self.native.dashboard.rel_mov_j_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user=_opt(user),
            a=_opt(accel),
            v=_opt(speed),
        )

    def rel_mov_l_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        tool: int | None = None,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative linear move in tool coordinate system."""
        return self.native.dashboard.rel_mov_l_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user=_opt(user),
            tool=_opt(tool),
            a=_opt(accel),
            v=_opt(speed),
        )

    def rel_mov_l_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative linear move in user coordinate system."""
        return self.native.dashboard.rel_mov_l_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user=_opt(user),
            a=_opt(accel),
            v=_opt(speed),
        )
