from __future__ import annotations
"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from .api_namespaces import (
    Config, Conveyor, ErrorHandling, Feedback, Io, Lifecycle, Motion,
    Modbus, Query, Raw, RelativeMotion, System, Welding, ForceControl
)
from .exceptions import NotSupportedError

if TYPE_CHECKING:
    import numpy as np
    from .types import Pose
    from dobot_api_v3 import DobotRobot as V3Robot


# ============================================================================
# V3 NAMESPACE IMPLEMENTATIONS
# ============================================================================



def _pose_from_tuple(t: tuple[float, ...]) -> Pose:
    """Convert a V3 Pose (plain tuple) to our unified Pose dataclass."""
    return Pose(x=t[0], y=t[1], z=t[2], rx=t[3], ry=t[4], rz=t[5])


def _build_dyn_params(
    *,
    speed_j: int | None = None,
    speed_l: int | None = None,
    accel_j: int | None = None,
    accel_l: int | None = None,
    speed: int | None = None,
    accel: int | None = None,
    cp: int | None = None,
    user: int | None = None,
    tool: int | None = None,
) -> list[str]:
    """Build a list of V3-style DynParam strings from keyword arguments."""
    params: list[str] = []
    if speed_j is not None:
        params.append(f"SpeedJ={speed_j}")
    if speed_l is not None:
        params.append(f"SpeedL={speed_l}")
    if accel_j is not None:
        params.append(f"AccJ={accel_j}")
    if accel_l is not None:
        params.append(f"AccL={accel_l}")
    if speed is not None:
        params.append(f"SpeedJ={speed}")
    if accel is not None:
        params.append(f"AccJ={accel}")
    if cp is not None:
        params.append(f"CP={cp}")
    if user is not None:
        params.append(f"User={user}")
    if tool is not None:
        params.append(f"Tool={tool}")
    return params




class ConfigV3(Config):
    """Concrete Config implementation for V3 API."""

    def acc_j(self, speed: int) -> None:
        """Set maximum joint acceleration (%)."""
        self.native.dashboard.acc_j(speed)

    def acc_l(self, speed: int) -> None:
        """Set maximum Cartesian acceleration (mm/s²)."""
        self.native.dashboard.acc_l(speed)

    def cp(self, ratio: int) -> None:
        """Set continuous-path blending ratio."""
        self.native.dashboard.cp(ratio)

    def set_collision_level(self, level: int) -> None:
        """Set collision detection sensitivity level."""
        self.native.dashboard.set_collision_level(level)

    def set_payload(
        self,
        weight: float,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
    ) -> None:
        """Set the tool payload."""
        self.native.dashboard.set_payload(
            weight, f"CenterX={center_x}", f"CenterY={center_y}", f"CenterZ={center_z}"
        )

    def set_tool(self, index: int) -> None:
        """Select the active tool coordinate system."""
        self.native.dashboard.set_tool(index)

    def set_user(self, index: int) -> None:
        """Select the active user coordinate system."""
        self.native.dashboard.set_user(index)

    def vel_j(self, speed: int) -> None:
        """Set maximum joint velocity (%)."""
        self.native.dashboard.vel_j(speed)

    def vel_l(self, speed: int) -> None:
        """Set maximum Cartesian velocity (mm/s)."""
        self.native.dashboard.vel_l(speed)

class ErrorHandlingV3(ErrorHandling):
    """Concrete ErrorHandling implementation for V3 API."""

    def check_errors(self, language: str = "en") -> bool:
        """Return ``True`` if the controller has active alarms."""
        return self.native.check_errors(language=language)

    def clear_and_recover(self, language: str = "en") -> bool:
        """Attempt to clear errors. Returns ``True`` on success."""
        return self.native.clear_and_recover(language=language)

class FeedbackV3(Feedback):
    """Concrete Feedback implementation for V3 API."""

    def feedback_data(self, port: int = 30004) -> object | None:
        """Return the latest real-time feedback packet."""
        fb = self._get_feedback(port)
        return fb.feedback_data() if fb else None

    def raw_feedback_data(self, port: int = 30004) -> np.ndarray | None:
        """Return the raw numpy feedback array."""
        fb = self._get_feedback(port)
        return fb.raw_feedback_data() if fb else None

class IoV3(Io):
    """Concrete Io implementation for V3 API."""

    if TYPE_CHECKING:
        native: V3Robot

    def ai(self, index: int) -> int:
        return self.native.ai(index)

    def ao(self, index: int, value: float) -> None:
        """Set an analogue output."""
        self.native.dashboard.ao(index, value)

    def ao_instant(self, index: int, value: float) -> None:
        self.native.ao_instant(index, value)

    def di(self, index: int) -> int:
        """Read a digital input."""
        return self.native.dashboard.di(index)

    def do_instant(self, index: int, status: int) -> None:
        self.native.do_instant(index, status)

    def do_output(self, index: int, status: int) -> None:
        """Set a digital output."""
        self.native.dashboard.do_output(index, status)

    def get_ao(self, index: int) -> float:
        return self.native.get_ao(index)

    def get_do(self, index: int) -> int:
        return self.native.get_do(index)

    def get_tool_do(self, index: int) -> int:
        return self.native.get_tool_do(index)

    def tool_ai(self, index: int) -> int:
        return self.native.tool_ai(index)

    def tool_di(self, index: int) -> int:
        """Read a tool digital input."""
        return self.native.dashboard.tool_di(index)

    def tool_do(self, index: int, status: int) -> None:
        """Set a tool digital output."""
        self.native.dashboard.tool_do(index, status)

    def tool_do_instant(self, index: int, status: int) -> None:
        self.native.tool_do_instant(index, status)

class LifecycleV3(Lifecycle):
    """Concrete Lifecycle implementation for V3 API."""

    def disconnect(self) -> None:
        """Close all TCP connections."""
        if self.native is not None:
            self.native.close()
            self.native = None  # type: ignore[assignment]

    def reconnect(self) -> None:
        """Re-establish all TCP connections."""
        self.native.reconnect()

    def shutdown(self) -> None:
        """Gracefully disable the robot arm."""
        self.native.shutdown()

    def startup(
        self,
        speed: int = 40,
        load: float = 0.0,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
        *,
        power_on_wait: float = 15.0,
    ) -> None:
        """Run the standard V3 startup sequence."""
        self.native.startup(
            speed=speed,
            load=load,
            center_x=center_x,
            center_y=center_y,
            center_z=center_z,
            power_on_wait=power_on_wait,
        )

class ModbusV3(Modbus):
    """Concrete Modbus implementation for V3 API."""

    def get_hold_regs(self, index: int, addr: int, count: int, val_type: str = "") -> list | int | float:
        return self.native.get_hold_regs(index, addr, count, val_type)

    def modbus_close(self, index: int) -> None:
        self.native.modbus_close(index)

    def modbus_create(self, ip: str, port: int, slave_id: int, is_rtu: int = -1) -> int:
        return self.native.modbus_create(ip, port, slave_id, is_rtu)

    def set_hold_regs(self, index: int, addr: int, count: int, val_tab: str | list, val_type: str = "") -> None:
        self.native.set_hold_regs(index, addr, count, val_tab, val_type)

class MotionV3(Motion):
    """Concrete Motion implementation for V3 API."""

    def arc(
        self,
        x1: float,
        y1: float,
        z1: float,
        rx1: float,
        ry1: float,
        rz1: float,
        x2: float,
        y2: float,
        z2: float,
        rx2: float,
        ry2: float,
        rz2: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Circular arc move through two via-points."""
        dyn = _build_dyn_params(
            speed_l=speed, accel_l=accel, cp=cp, user=user, tool=tool
        )
        return self.native.arc(
            x1, y1, z1, rx1, ry1, rz1, x2, y2, z2, rx2, ry2, rz2, *dyn
        )

    def circle(
        self,
        x1: float,
        y1: float,
        z1: float,
        rx1: float,
        ry1: float,
        rz1: float,
        x2: float,
        y2: float,
        z2: float,
        rx2: float,
        ry2: float,
        rz2: float,
        *,
        count: int = 1,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        raise NotSupportedError()

    def get_start_pose(self, trace_name: str) -> Pose:
        return self.native.get_start_pose(trace_name)

    def joint_mov_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
    ) -> int:
        """Joint-space move with joint-angle targets."""
        dyn = _build_dyn_params(speed_j=speed, accel_j=accel, cp=cp)
        return self.native.joint_mov_j(j1, j2, j3, j4, j5, j6, *dyn)

    def mov_j(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Joint-space move to a Cartesian target."""
        dyn = _build_dyn_params(
            speed_j=speed, accel_j=accel, cp=cp, user=user, tool=tool
        )
        return self.native.mov_j(x, y, z, rx, ry, rz, *dyn)

    def mov_l(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Linear move."""
        dyn = _build_dyn_params(
            speed_l=speed, accel_l=accel, cp=cp, user=user, tool=tool
        )
        return self.native.mov_l(x, y, z, rx, ry, rz, *dyn)

    def move_jog(self, axis_id: str = "") -> int:
        """Start or stop jog motion."""
        return self.native.move_jog(axis_id)

    def servo_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        t: float = 0.1,
        lookahead_time: float = 50.0,
        gain: float = 500.0,
    ) -> int:
        """Servo (streaming) move in joint space."""
        return self.native.servo_j(
            j1, j2, j3, j4, j5, j6, t=t, lookahead_time=lookahead_time, gain=gain
        )

    def servo_p(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
    ) -> int:
        """Servo (streaming) move in Cartesian space."""
        return self.native.servo_p(x, y, z, rx, ry, rz)

    def start_path(
        self,
        trace_name: str,
        *,
        is_const: int = -1,
        multi: float = -1.0,
    ) -> int:
        return self.native.start_path(trace_name, is_const, multi)

    def sync(self) -> None:
        """Block until all queued motion commands have completed."""
        self.native.sync()

class QueryV3(Query):
    """Concrete Query implementation for V3 API."""

    def get_angle(self) -> Pose:
        """Return the current joint angles (as a Pose with j1-j6 in x-rz)."""
        return _pose_from_tuple(self.native.get_angle())

    def get_current_command_id(self) -> int:
        return self.native.get_current_command_id()

    def get_error_id(self) -> tuple[int, ...]:
        """Return a tuple of currently-active error IDs."""
        return self.native.get_error_id()

    def get_pose(self) -> Pose:
        """Return the current Cartesian pose."""
        return _pose_from_tuple(self.native.get_pose())

    def inverse_kin(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        *,
        user: int = -1,
        tool: int = -1,
    ) -> Pose:
        return self.native.inverse_kin(x, y, z, rx, ry, rz, user, tool)

    def positive_kin(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        user: int = -1,
        tool: int = -1,
    ) -> Pose:
        return self.native.positive_kin(j1, j2, j3, j4, j5, j6, user, tool)

    def robot_mode(self) -> int:
        """Return the current robot mode."""
        return self.native.robot_mode()

    def start_drag(self) -> None:
        """Enter drag/teach mode."""
        self.native.start_drag()

    def stop_drag(self) -> None:
        """Exit drag/teach mode."""
        self.native.stop_drag()

class RawV3(Raw):
    """Concrete Raw implementation for V3 API."""

    def send_raw(self, command: str) -> str:
        """Send a raw TCP command string and return the raw response."""
        return self.native.dashboard.send_recv_msg(command)

class RelativeMotionV3(RelativeMotion):
    """Concrete RelativeMotion implementation for V3 API."""

    def rel_joint_mov_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative move with joint offsets."""
        dyn = _build_dyn_params(speed_j=speed, accel_j=accel)
        return self.native.move.rel_joint_mov_j(j1, j2, j3, j4, j5, j6, *dyn)

    def rel_mov_j_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        tool: int | None = None,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative joint move in tool coordinate system."""
        tool_val = tool if tool is not None else 0
        return self.native.move.rel_mov_j_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            tool_val,
        )

    def rel_mov_j_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative joint move in user coordinate system."""
        user_val = user if user is not None else 0
        dyn = _build_dyn_params(speed_j=speed, accel_j=accel)
        return self.native.move.rel_mov_j_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user_val,
            *dyn,
        )

    def rel_mov_l_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        tool: int | None = None,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative linear move in tool coordinate system."""
        tool_val = tool if tool is not None else 0
        return self.native.move.rel_mov_l_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            tool_val,
        )

    def rel_mov_l_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative linear move in user coordinate system."""
        user_val = user if user is not None else 0
        dyn = _build_dyn_params(speed_l=speed, accel_l=accel)
        return self.native.move.rel_mov_l_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user_val,
            *dyn,
        )

class SystemV3(System):
    """Concrete System implementation for V3 API."""

    def clear_error(self) -> None:
        """Clear controller error/alarm information."""
        self.native.clear_error()

    def disable_robot(self) -> None:
        """Disable the robot."""
        self.native.disable_robot()

    def emergency_stop(self) -> None:
        """Trigger an emergency stop."""
        self.native.emergency_stop()

    def enable_robot(
        self,
        load: float = 0.0,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
    ) -> None:
        """Enable the robot."""
        self.native.enable_robot(
            load=load, center_x=center_x, center_y=center_y, center_z=center_z
        )

    def pause_script(self) -> None:
        self.native.pause_script()

    def power_on(self) -> None:
        """Power on the robot."""
        self.native.power_on()

    def reset_robot(self) -> None:
        """Reset the robot controller."""
        self.native.reset_robot()

    def resume_script(self) -> None:
        self.native.resume_script()

    def run_script(self, project_name: str) -> None:
        self.native.run_script(project_name)

    def speed_factor(self, speed: int) -> None:
        """Set the global speed factor (1-100)."""
        self.native.speed_factor(speed)

    def stop_script(self) -> None:
        self.native.stop_script()


__all__ = [
    "ConfigV3",
    "ErrorHandlingV3",
    "FeedbackV3",
    "IoV3",
    "LifecycleV3",
    "ModbusV3",
    "MotionV3",
    "QueryV3",
    "RawV3",
    "RelativeMotionV3",
    "SystemV3"
]
