from __future__ import annotations
"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from .api_namespaces import (
    Config, Conveyor, ErrorHandling, Feedback, Io, Lifecycle, Motion,
    Modbus, Query, Raw, RelativeMotion, System, Welding, ForceControl
)
from .exceptions import NotSupportedError

if TYPE_CHECKING:
    import numpy as np
    from .types import Pose


# ============================================================================
# V4 NAMESPACE IMPLEMENTATIONS
# ============================================================================



def _opt(val: int | None) -> int:
    # helper for converting None to -1 in options
    return val if val is not None else -1


def _pose_from_v4(v4_pose: V4Pose) -> Pose:
    """Convert a V4 ``dobot_api_v4.Pose`` to our unified :class:`Pose`."""
    return Pose(
        x=v4_pose.x,
        y=v4_pose.y,
        z=v4_pose.z,
        rx=v4_pose.rx,
        ry=v4_pose.ry,
        rz=v4_pose.rz,
    )




class ConfigV4(Config):
    """Concrete Config implementation for V4 API."""

    def acc_j(self, speed: int) -> None:
        """Set maximum joint acceleration (%)."""
        self.native.acc_j(speed)

    def acc_l(self, speed: int) -> None:
        """Set maximum Cartesian acceleration (mm/s²)."""
        self.native.acc_l(speed)

    def cp(self, ratio: int) -> None:
        """Set continuous-path blending ratio."""
        self.native.cp(ratio)

    def set_collision_level(self, level: int) -> None:
        """Set collision detection sensitivity level."""
        self.native.dashboard.set_collision_level(level)

    def set_payload(
        self,
        weight: float,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
    ) -> None:
        """Set the tool payload."""
        self.native.dashboard.set_payload(
            load=weight, x=center_x, y=center_y, z=center_z
        )

    def set_tool(self, index: int) -> None:
        """Select the active tool coordinate system."""
        self.native.dashboard.tool(index)

    def set_user(self, index: int) -> None:
        """Select the active user coordinate system."""
        self.native.dashboard.user(index)

    def vel_j(self, speed: int) -> None:
        """Set maximum joint velocity (%)."""
        self.native.vel_j(speed)

    def vel_l(self, speed: int) -> None:
        """Set maximum Cartesian velocity (mm/s)."""
        self.native.vel_l(speed)

class ConveyorV4(Conveyor):
    """Concrete Conveyor implementation for V4 API."""

    def cnv_init(self, index: int) -> None:
        self.native.cnv_init(index)

class ErrorHandlingV4(ErrorHandling):
    """Concrete ErrorHandling implementation for V4 API."""

    def check_errors(self, language: str = "en") -> bool:
        """Return ``True`` if the controller has active alarms."""
        return self.native.check_errors(language=language)

    def clear_and_recover(self, language: str = "en") -> bool:
        """Attempt to clear errors. Returns ``True`` on success."""
        return self.native.clear_robot_error(language=language)

class FeedbackV4(Feedback):
    """Concrete Feedback implementation for V4 API."""

    def feedback_data(self, port: int = 30004) -> object | None:
        """Return the latest real-time feedback packet."""
        fb = self._get_feedback(port)
        return fb.feedback_data() if fb else None

    def raw_feedback_data(self, port: int = 30004) -> np.ndarray | None:
        """Return the raw numpy feedback array."""
        fb = self._get_feedback(port)
        return fb.raw_feedback_data() if fb else None

class ForceControlV4(ForceControl):
    """Concrete ForceControl implementation for V4 API."""

    def enable_ft_sensor(self, status: int) -> None:
        """Enable or disable the force/torque sensor."""
        self.native.dashboard.enable_ft_sensor(status)

    def fc_off(self) -> None:
        """Turn off force-compliance mode."""
        self.native.fc_off()

    def get_force(self) -> Pose:
        """Return force/torque readings from the sensor."""
        return _pose_from_v4(self.native.get_force())

    def six_force_home(self) -> None:
        """Zero (home) the six-axis force/torque sensor."""
        self.native.dashboard.six_force_home()

class IoV4(Io):
    """Concrete Io implementation for V4 API."""

    def ai(self, index: int) -> int:
        """Read an analogue input."""
        return self.native.dashboard.ai(index)

    def ao(self, index: int, value: float) -> None:
        """Set an analogue output."""
        self.native.ao(index, value)

    def ao_instant(self, index: int, value: float) -> None:
        """Set an analogue output immediately."""
        self.native.dashboard.ao_instant(index, value)

    def di(self, index: int) -> int:
        """Read a digital input."""
        return self.native.di(index)

    def do_instant(self, index: int, status: int) -> None:
        """Set a digital output immediately (bypasses the motion queue)."""
        self.native.dashboard.do_instant(index, status)

    def do_output(self, index: int, status: int) -> None:
        """Set a digital output."""
        self.native.do_output(index, status)

    def get_ao(self, index: int) -> float:
        """Read the current value of an analogue output."""
        return float(self.native.dashboard.get_ao(index))

    def get_do(self, index: int) -> int:
        """Read the current status of a digital output."""
        return self.native.get_do(index)

    def get_tool_do(self, index: int) -> int:
        """Read the current status of a tool digital output."""
        return self.native.dashboard.get_tool_do(index)

    def tool_ai(self, index: int) -> int:
        """Read a tool analogue input."""
        return self.native.dashboard.tool_ai(index)

    def tool_di(self, index: int) -> int:
        """Read a tool digital input."""
        return self.native.dashboard.tool_di(index)

    def tool_do(self, index: int, status: int) -> None:
        """Set a tool digital output."""
        self.native.dashboard.tool_do(index, status)

    def tool_do_instant(self, index: int, status: int) -> None:
        """Set a tool digital output immediately."""
        self.native.dashboard.tool_do_instant(index, status)

class LifecycleV4(Lifecycle):
    """Concrete Lifecycle implementation for V4 API."""

    def disconnect(self) -> None:
        """Close all TCP connections."""
        if self.native is not None:
            self.native.close()
            self.native = None  # type: ignore[assignment]

    def reconnect(self) -> None:
        """Re-establish all TCP connections."""
        self.native.reconnect()

    def shutdown(self) -> None:
        """Gracefully disable the robot arm."""
        logger.info("V4 shutdown: disabling robot")
        self.native.disable_robot()

    def startup(
        self,
        speed: int = 40,
        load: float = 0.0,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
        *,
        power_on_wait: float = 15.0,
    ) -> None:
        """V4 startup — composed manually since there's no built-in startup()."""
        logger.info("V4 startup sequence starting")
        has_errors = self.native.check_errors(language=self._language)
        if has_errors:
            logger.info("Errors detected — clearing and powering on")
            self.native.clear_error()
            self.native.power_on()
            logger.info(f"Waiting {power_on_wait}s for controller to power on")
            time.sleep(power_on_wait)
        else:
            logger.info("No errors detected — skipping clear_error and power_on")
        self.native.disable_robot()
        self.native.enable_robot(
            load=load,
            center_x=center_x,
            center_y=center_y,
            center_z=center_z,
        )
        self.native.speed_factor(speed)
        logger.info("V4 startup sequence complete")

class ModbusV4(Modbus):
    """Concrete Modbus implementation for V4 API."""

    def get_hold_regs(self, index: int, addr: int, count: int, val_type: str = "") -> list | int | float:
        return self.native.get_hold_regs(index, addr, count, val_type)

    def modbus_close(self, index: int) -> None:
        self.native.modbus_close(index)

    def modbus_create(self, ip: str, port: int, slave_id: int, is_rtu: int = -1) -> int:
        return self.native.modbus_create(ip, port, slave_id, is_rtu)

    def set_hold_regs(self, index: int, addr: int, count: int, val_tab: str | list, val_type: str = "") -> None:
        self.native.set_hold_regs(index, addr, count, val_tab, val_type)

class MotionV4(Motion):
    """Concrete Motion implementation for V4 API."""

    def arc(
        self,
        x1: float,
        y1: float,
        z1: float,
        rx1: float,
        ry1: float,
        rz1: float,
        x2: float,
        y2: float,
        z2: float,
        rx2: float,
        ry2: float,
        rz2: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Circular arc move through two via-points."""
        return self.native.arc(
            x1,
            y1,
            z1,
            rx1,
            ry1,
            rz1,
            x2,
            y2,
            z2,
            rx2,
            ry2,
            rz2,
            coordinate_mode=0,
            user=_opt(user),
            tool=_opt(tool),
            a=_opt(accel),
            v=_opt(speed),
            cp=_opt(cp),
        )

    def circle(
        self,
        x1: float,
        y1: float,
        z1: float,
        rx1: float,
        ry1: float,
        rz1: float,
        x2: float,
        y2: float,
        z2: float,
        rx2: float,
        ry2: float,
        rz2: float,
        *,
        count: int = 1,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Full-circle interpolated motion through two via-points."""
        return self.native.circle(
            x1,
            y1,
            z1,
            rx1,
            ry1,
            rz1,
            x2,
            y2,
            z2,
            rx2,
            ry2,
            rz2,
            coordinate_mode=0,
            count=count,
            user=_opt(user),
            tool=_opt(tool),
            a=_opt(accel),
            v=_opt(speed),
            cp=_opt(cp),
        )

    def get_start_pose(self, trace_name: str) -> Pose:
        """Return the starting pose of a recorded trajectory."""
        return _pose_from_v4(self.native.dashboard.get_start_pose(trace_name))

    def joint_mov_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
    ) -> int:
        """Joint-space move with joint-angle targets."""
        return self.native.mov_j(
            j1,
            j2,
            j3,
            j4,
            j5,
            j6,
            coordinate_mode=1,
            a=_opt(accel),
            v=_opt(speed),
            cp=_opt(cp),
        )

    def mov_j(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Joint-space move to a Cartesian target."""
        return self.native.mov_j(
            x,
            y,
            z,
            rx,
            ry,
            rz,
            coordinate_mode=0,
            user=_opt(user),
            tool=_opt(tool),
            a=_opt(accel),
            v=_opt(speed),
            cp=_opt(cp),
        )

    def mov_l(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Linear move."""
        return self.native.mov_l(
            x,
            y,
            z,
            rx,
            ry,
            rz,
            coordinate_mode=0,
            user=_opt(user),
            tool=_opt(tool),
            a=_opt(accel),
            v=_opt(speed),
            speed=_opt(speed),
            cp=_opt(cp),
        )

    def move_jog(self, axis_id: str = "") -> int:
        """Start or stop jog motion."""
        self.native.move_jog(axis_id=axis_id)
        return 0  # V4 move_jog returns None

    def servo_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        t: float = 0.1,
        lookahead_time: float = 50.0,
        gain: float = 500.0,
    ) -> int:
        """Servo (streaming) move in joint space."""
        return self.native.servo_j(
            j1, j2, j3, j4, j5, j6, t=t, ahead_time=lookahead_time, gain=gain
        )

    def servo_p(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
    ) -> int:
        """Servo (streaming) move in Cartesian space."""
        return self.native.servo_p(x, y, z, rx, ry, rz)

    def start_path(
        self,
        trace_name: str,
        *,
        is_const: int = -1,
        multi: float = -1.0,
    ) -> int:
        """Play back a recorded trajectory file."""
        return self.native.dashboard.start_path(
            trace_name, is_const=is_const, multi=multi
        )

    def sync(self) -> None:
        """Block until all queued motion commands have completed.

        V4 has no native ``sync()`` — polls ``get_current_command_id()``.
        """
        logger.debug("V4 sync: polling get_current_command_id()")
        while True:
            cmd_id = self.native.get_current_command_id()
            if cmd_id == 0:
                break
            time.sleep(0.1)

class QueryV4(Query):
    """Concrete Query implementation for V4 API."""

    def get_angle(self) -> Pose:
        """Return the current joint angles (as a Pose with j1-j6 in x-rz)."""
        return _pose_from_v4(self.native.get_angle())

    def get_current_command_id(self) -> int:
        """Return the queue ID of the currently executing command."""
        return self.native.get_current_command_id()

    def get_error_id(self) -> tuple[int, ...]:
        """Return a tuple of currently-active error IDs."""
        return self.native.get_error_id()

    def get_pose(self) -> Pose:
        """Return the current Cartesian pose."""
        return _pose_from_v4(self.native.get_pose())

    def inverse_kin(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        *,
        user: int = -1,
        tool: int = -1,
    ) -> Pose:
        """Inverse kinematics — Cartesian pose to joint angles."""
        return _pose_from_v4(
            self.native.inverse_kin(x, y, z, rx, ry, rz, user=user, tool=tool)
        )

    def positive_kin(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        user: int = -1,
        tool: int = -1,
    ) -> Pose:
        """Forward kinematics — joint angles to Cartesian pose."""
        return _pose_from_v4(
            self.native.positive_kin(j1, j2, j3, j4, j5, j6, user=user, tool=tool)
        )

    def robot_mode(self) -> int:
        """Return the current robot mode."""
        return self.native.robot_mode()

    def start_drag(self) -> None:
        """Enter drag/teach mode."""
        self.native.start_drag()

    def stop_drag(self) -> None:
        """Exit drag/teach mode."""
        self.native.stop_drag()

class RawV4(Raw):
    """Concrete Raw implementation for V4 API."""

    def send_raw(self, command: str) -> str:
        """Send a raw TCP command string and return the raw response."""
        return self.native.dashboard.send_recv_msg(command)

class RelativeMotionV4(RelativeMotion):
    """Concrete RelativeMotion implementation for V4 API."""

    def rel_joint_mov_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative move with joint offsets."""
        return self.native.dashboard.rel_joint_mov_j(
            j1,
            j2,
            j3,
            j4,
            j5,
            j6,
            a=_opt(accel),
            v=_opt(speed),
        )

    def rel_mov_j_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        tool: int | None = None,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative joint move in tool coordinate system."""
        return self.native.dashboard.rel_mov_j_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user=_opt(user),
            tool=_opt(tool),
            a=_opt(accel),
            v=_opt(speed),
        )

    def rel_mov_j_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative joint move in user coordinate system."""
        return self.native.dashboard.rel_mov_j_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user=_opt(user),
            a=_opt(accel),
            v=_opt(speed),
        )

    def rel_mov_l_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        tool: int | None = None,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative linear move in tool coordinate system."""
        return self.native.dashboard.rel_mov_l_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user=_opt(user),
            tool=_opt(tool),
            a=_opt(accel),
            v=_opt(speed),
        )

    def rel_mov_l_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative linear move in user coordinate system."""
        return self.native.dashboard.rel_mov_l_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user=_opt(user),
            a=_opt(accel),
            v=_opt(speed),
        )

class SystemV4(System):
    """Concrete System implementation for V4 API."""

    def clear_error(self) -> None:
        """Clear controller error/alarm information."""
        self.native.clear_error()

    def disable_robot(self) -> None:
        """Disable the robot."""
        self.native.disable_robot()

    def emergency_stop(self) -> None:
        """Trigger an emergency stop."""
        self.native.emergency_stop(mode=0)

    def enable_robot(
        self,
        load: float = 0.0,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
    ) -> None:
        """Enable the robot."""
        self.native.enable_robot(
            load=load, center_x=center_x, center_y=center_y, center_z=center_z
        )

    def pause_script(self) -> None:
        """Pause the running script or motion queue."""
        self.native.dashboard.pause_script()

    def power_on(self) -> None:
        """Power on the robot."""
        self.native.power_on()

    def reset_robot(self) -> None:
        """Reset the robot controller."""
        self.native.reset_robot()

    def resume_script(self) -> None:
        """Resume a paused script or motion queue."""
        self.native.dashboard.resume()

    def run_script(self, project_name: str) -> None:
        """Run a project/script on the controller."""
        self.native.dashboard.run_script(project_name)

    def speed_factor(self, speed: int) -> None:
        """Set the global speed factor (1–100)."""
        self.native.speed_factor(speed)

    def stop_script(self) -> None:
        """Stop the running script or motion queue."""
        self.native.dashboard.stop_script()

class WeldingV4(Welding):
    """Concrete Welding implementation for V4 API."""

    def weave_start(self) -> None:
        self.native.weave_start()


__all__ = [
    "ConfigV4",
    "ConveyorV4",
    "ErrorHandlingV4",
    "FeedbackV4",
    "ForceControlV4",
    "IoV4",
    "LifecycleV4",
    "ModbusV4",
    "MotionV4",
    "QueryV4",
    "RawV4",
    "RelativeMotionV4",
    "SystemV4",
    "WeldingV4"
]
