"""Motion-check extension — V4-only (CR / Nova 2s / Nova NG)."""

from __future__ import annotations

from .base import ExtensionNamespace


class MotionCheck(ExtensionNamespace):
    """Pre-flight motion validation (collision / reachability checks).

    Available only on V4 robots.  Access via ``robot.check``.
    """

    _feature_name = "Motion check"

    def check_mov_j(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        *,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        """Check a joint move for reachability / collision."""
        self._require_v4().check_mov_j(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            user=user,
            tool=tool,
            a=a,
            v=v,
            cp=cp,
        )

    def check_mov_l(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        *,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        """Check a linear move for reachability / collision."""
        self._require_v4().check_mov_l(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            user=user,
            tool=tool,
            a=a,
            v=v,
            cp=cp,
        )

    def check_mov_c(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        j1c: float,
        j2c: float,
        j3c: float,
        j4c: float,
        j5c: float,
        j6c: float,
        *,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        """Check a circular move for reachability / collision."""
        self._require_v4().check_mov_c(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            j1c,
            j2c,
            j3c,
            j4c,
            j5c,
            j6c,
            user=user,
            tool=tool,
            a=a,
            v=v,
            cp=cp,
        )

    def check_odd_mov_j(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        *,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        """Odd-segment check for joint move."""
        self._require_v4().check_odd_mov_j(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            user=user,
            tool=tool,
            a=a,
            v=v,
            cp=cp,
        )

    def check_odd_mov_l(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        *,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        """Odd-segment check for linear move."""
        self._require_v4().check_odd_mov_l(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            user=user,
            tool=tool,
            a=a,
            v=v,
            cp=cp,
        )

    def check_odd_mov_c(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        j1c: float,
        j2c: float,
        j3c: float,
        j4c: float,
        j5c: float,
        j6c: float,
        *,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        """Odd-segment check for circular move."""
        self._require_v4().check_odd_mov_c(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            j1c,
            j2c,
            j3c,
            j4c,
            j5c,
            j6c,
            user=user,
            tool=tool,
            a=a,
            v=v,
            cp=cp,
        )
