from __future__ import annotations

"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    Config,
)

if TYPE_CHECKING:
    from ..types import Pose


# ============================================================================
# V3 NAMESPACE IMPLEMENTATIONS
# ============================================================================


def _pose_from_tuple(t: tuple[float, ...]) -> Pose:
    """Convert a V3 Pose (plain tuple) to our unified Pose dataclass."""
    return Pose(x=t[0], y=t[1], z=t[2], rx=t[3], ry=t[4], rz=t[5])


def _build_dyn_params(
    *,
    speed_j: int | None = None,
    speed_l: int | None = None,
    accel_j: int | None = None,
    accel_l: int | None = None,
    speed: int | None = None,
    accel: int | None = None,
    cp: int | None = None,
    user: int | None = None,
    tool: int | None = None,
) -> list[str]:
    """Build a list of V3-style DynParam strings from keyword arguments."""
    params: list[str] = []
    if speed_j is not None:
        params.append(f"SpeedJ={speed_j}")
    if speed_l is not None:
        params.append(f"SpeedL={speed_l}")
    if accel_j is not None:
        params.append(f"AccJ={accel_j}")
    if accel_l is not None:
        params.append(f"AccL={accel_l}")
    if speed is not None:
        params.append(f"SpeedJ={speed}")
    if accel is not None:
        params.append(f"AccJ={accel}")
    if cp is not None:
        params.append(f"CP={cp}")
    if user is not None:
        params.append(f"User={user}")
    if tool is not None:
        params.append(f"Tool={tool}")
    return params


class ConfigV3(Config):
    """Concrete Config implementation for V3 API."""

    def acc_j(self, speed: int) -> None:
        """Set maximum joint acceleration (%)."""
        self.native.dashboard.acc_j(speed)

    def acc_l(self, speed: int) -> None:
        """Set maximum Cartesian acceleration (mm/s²)."""
        self.native.dashboard.acc_l(speed)

    def cp(self, ratio: int) -> None:
        """Set continuous-path blending ratio."""
        self.native.dashboard.cp(ratio)

    def set_collision_level(self, level: int) -> None:
        """Set collision detection sensitivity level."""
        self.native.dashboard.set_collision_level(level)

    def set_payload(
        self,
        weight: float,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
    ) -> None:
        """Set the tool payload."""
        self.native.dashboard.set_payload(weight, f"CenterX={center_x}", f"CenterY={center_y}", f"CenterZ={center_z}")

    def set_tool(self, index: int) -> None:
        """Select the active tool coordinate system."""
        self.native.dashboard.set_tool(index)

    def set_user(self, index: int) -> None:
        """Select the active user coordinate system."""
        self.native.dashboard.set_user(index)

    def vel_j(self, speed: int) -> None:
        """Set maximum joint velocity (%)."""
        self.native.dashboard.vel_j(speed)

    def vel_l(self, speed: int) -> None:
        """Set maximum Cartesian velocity (mm/s)."""
        self.native.dashboard.vel_l(speed)
