from __future__ import annotations
"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    Config, Conveyor, ErrorHandling, Feedback, Io, Lifecycle, Motion,
    Modbus, Query, Raw, RelativeMotion, System, Welding, ForceControl
)
from ..exceptions import NotSupportedError

if TYPE_CHECKING:
    import numpy as np
    from ..types import Pose
    from dobot_api_v3 import DobotRobot as V3Robot


# ============================================================================
# V3 NAMESPACE IMPLEMENTATIONS
# ============================================================================



def _pose_from_tuple(t: tuple[float, ...]) -> Pose:
    """Convert a V3 Pose (plain tuple) to our unified Pose dataclass."""
    return Pose(x=t[0], y=t[1], z=t[2], rx=t[3], ry=t[4], rz=t[5])


def _build_dyn_params(
    *,
    speed_j: int | None = None,
    speed_l: int | None = None,
    accel_j: int | None = None,
    accel_l: int | None = None,
    speed: int | None = None,
    accel: int | None = None,
    cp: int | None = None,
    user: int | None = None,
    tool: int | None = None,
) -> list[str]:
    """Build a list of V3-style DynParam strings from keyword arguments."""
    params: list[str] = []
    if speed_j is not None:
        params.append(f"SpeedJ={speed_j}")
    if speed_l is not None:
        params.append(f"SpeedL={speed_l}")
    if accel_j is not None:
        params.append(f"AccJ={accel_j}")
    if accel_l is not None:
        params.append(f"AccL={accel_l}")
    if speed is not None:
        params.append(f"SpeedJ={speed}")
    if accel is not None:
        params.append(f"AccJ={accel}")
    if cp is not None:
        params.append(f"CP={cp}")
    if user is not None:
        params.append(f"User={user}")
    if tool is not None:
        params.append(f"Tool={tool}")
    return params




class ErrorHandlingV3(ErrorHandling):
    """Concrete ErrorHandling implementation for V3 API."""

    def check_errors(self, language: str = "en") -> bool:
        """Return ``True`` if the controller has active alarms."""
        return self.native.check_errors(language=language)

    def clear_and_recover(self, language: str = "en") -> bool:
        """Attempt to clear errors. Returns ``True`` on success."""
        return self.native.clear_and_recover(language=language)
