from __future__ import annotations
"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    Config, Conveyor, ErrorHandling, Feedback, Io, Lifecycle, Motion,
    Modbus, Query, Raw, RelativeMotion, System, Welding, ForceControl
)
from ..exceptions import NotSupportedError

if TYPE_CHECKING:
    import numpy as np
    from ..types import Pose
    from dobot_api_v3 import DobotRobot as V3Robot


# ============================================================================
# V3 NAMESPACE IMPLEMENTATIONS
# ============================================================================



def _pose_from_tuple(t: tuple[float, ...]) -> Pose:
    """Convert a V3 Pose (plain tuple) to our unified Pose dataclass."""
    return Pose(x=t[0], y=t[1], z=t[2], rx=t[3], ry=t[4], rz=t[5])


def _build_dyn_params(
    *,
    speed_j: int | None = None,
    speed_l: int | None = None,
    accel_j: int | None = None,
    accel_l: int | None = None,
    speed: int | None = None,
    accel: int | None = None,
    cp: int | None = None,
    user: int | None = None,
    tool: int | None = None,
) -> list[str]:
    """Build a list of V3-style DynParam strings from keyword arguments."""
    params: list[str] = []
    if speed_j is not None:
        params.append(f"SpeedJ={speed_j}")
    if speed_l is not None:
        params.append(f"SpeedL={speed_l}")
    if accel_j is not None:
        params.append(f"AccJ={accel_j}")
    if accel_l is not None:
        params.append(f"AccL={accel_l}")
    if speed is not None:
        params.append(f"SpeedJ={speed}")
    if accel is not None:
        params.append(f"AccJ={accel}")
    if cp is not None:
        params.append(f"CP={cp}")
    if user is not None:
        params.append(f"User={user}")
    if tool is not None:
        params.append(f"Tool={tool}")
    return params




class MotionV3(Motion):
    """Concrete Motion implementation for V3 API."""

    def arc(
        self,
        x1: float,
        y1: float,
        z1: float,
        rx1: float,
        ry1: float,
        rz1: float,
        x2: float,
        y2: float,
        z2: float,
        rx2: float,
        ry2: float,
        rz2: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Circular arc move through two via-points."""
        dyn = _build_dyn_params(
            speed_l=speed, accel_l=accel, cp=cp, user=user, tool=tool
        )
        return self.native.arc(
            x1, y1, z1, rx1, ry1, rz1, x2, y2, z2, rx2, ry2, rz2, *dyn
        )

    def circle(
        self,
        x1: float,
        y1: float,
        z1: float,
        rx1: float,
        ry1: float,
        rz1: float,
        x2: float,
        y2: float,
        z2: float,
        rx2: float,
        ry2: float,
        rz2: float,
        *,
        count: int = 1,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        raise NotSupportedError()

    def get_start_pose(self, trace_name: str) -> Pose:
        return self.native.get_start_pose(trace_name)

    def joint_mov_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
    ) -> int:
        """Joint-space move with joint-angle targets."""
        dyn = _build_dyn_params(speed_j=speed, accel_j=accel, cp=cp)
        return self.native.joint_mov_j(j1, j2, j3, j4, j5, j6, *dyn)

    def mov_j(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Joint-space move to a Cartesian target."""
        dyn = _build_dyn_params(
            speed_j=speed, accel_j=accel, cp=cp, user=user, tool=tool
        )
        return self.native.mov_j(x, y, z, rx, ry, rz, *dyn)

    def mov_l(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
        cp: int | None = None,
        user: int | None = None,
        tool: int | None = None,
    ) -> int:
        """Linear move."""
        dyn = _build_dyn_params(
            speed_l=speed, accel_l=accel, cp=cp, user=user, tool=tool
        )
        return self.native.mov_l(x, y, z, rx, ry, rz, *dyn)

    def move_jog(self, axis_id: str = "") -> int:
        """Start or stop jog motion."""
        return self.native.move_jog(axis_id)

    def servo_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        t: float = 0.1,
        lookahead_time: float = 50.0,
        gain: float = 500.0,
    ) -> int:
        """Servo (streaming) move in joint space."""
        return self.native.servo_j(
            j1, j2, j3, j4, j5, j6, t=t, lookahead_time=lookahead_time, gain=gain
        )

    def servo_p(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
    ) -> int:
        """Servo (streaming) move in Cartesian space."""
        return self.native.servo_p(x, y, z, rx, ry, rz)

    def start_path(
        self,
        trace_name: str,
        *,
        is_const: int = -1,
        multi: float = -1.0,
    ) -> int:
        return self.native.start_path(trace_name, is_const, multi)

    def sync(self) -> None:
        """Block until all queued motion commands have completed."""
        self.native.sync()
