from __future__ import annotations

"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    Query,
)

if TYPE_CHECKING:
    from ..types import Pose


# ============================================================================
# V3 NAMESPACE IMPLEMENTATIONS
# ============================================================================


def _pose_from_tuple(t: tuple[float, ...]) -> Pose:
    """Convert a V3 Pose (plain tuple) to our unified Pose dataclass."""
    return Pose(x=t[0], y=t[1], z=t[2], rx=t[3], ry=t[4], rz=t[5])


def _build_dyn_params(
    *,
    speed_j: int | None = None,
    speed_l: int | None = None,
    accel_j: int | None = None,
    accel_l: int | None = None,
    speed: int | None = None,
    accel: int | None = None,
    cp: int | None = None,
    user: int | None = None,
    tool: int | None = None,
) -> list[str]:
    """Build a list of V3-style DynParam strings from keyword arguments."""
    params: list[str] = []
    if speed_j is not None:
        params.append(f"SpeedJ={speed_j}")
    if speed_l is not None:
        params.append(f"SpeedL={speed_l}")
    if accel_j is not None:
        params.append(f"AccJ={accel_j}")
    if accel_l is not None:
        params.append(f"AccL={accel_l}")
    if speed is not None:
        params.append(f"SpeedJ={speed}")
    if accel is not None:
        params.append(f"AccJ={accel}")
    if cp is not None:
        params.append(f"CP={cp}")
    if user is not None:
        params.append(f"User={user}")
    if tool is not None:
        params.append(f"Tool={tool}")
    return params


class QueryV3(Query):
    """Concrete Query implementation for V3 API."""

    def get_angle(self) -> Pose:
        """Return the current joint angles (as a Pose with j1-j6 in x-rz)."""
        return _pose_from_tuple(self.native.get_angle())

    def get_current_command_id(self) -> int:
        return self.native.get_current_command_id()

    def get_error_id(self) -> tuple[int, ...]:
        """Return a tuple of currently-active error IDs."""
        return self.native.get_error_id()

    def get_pose(self) -> Pose:
        """Return the current Cartesian pose."""
        return _pose_from_tuple(self.native.get_pose())

    def inverse_kin(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        *,
        user: int = -1,
        tool: int = -1,
    ) -> Pose:
        return self.native.inverse_kin(x, y, z, rx, ry, rz, user, tool)

    def positive_kin(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        user: int = -1,
        tool: int = -1,
    ) -> Pose:
        return self.native.positive_kin(j1, j2, j3, j4, j5, j6, user, tool)

    def robot_mode(self) -> int:
        """Return the current robot mode."""
        return self.native.robot_mode()

    def start_drag(self) -> None:
        """Enter drag/teach mode."""
        self.native.start_drag()

    def stop_drag(self) -> None:
        """Exit drag/teach mode."""
        self.native.stop_drag()
