from __future__ import annotations

"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    RelativeMotion,
)

if TYPE_CHECKING:
    from ..types import Pose


# ============================================================================
# V3 NAMESPACE IMPLEMENTATIONS
# ============================================================================


def _pose_from_tuple(t: tuple[float, ...]) -> Pose:
    """Convert a V3 Pose (plain tuple) to our unified Pose dataclass."""
    return Pose(x=t[0], y=t[1], z=t[2], rx=t[3], ry=t[4], rz=t[5])


def _build_dyn_params(
    *,
    speed_j: int | None = None,
    speed_l: int | None = None,
    accel_j: int | None = None,
    accel_l: int | None = None,
    speed: int | None = None,
    accel: int | None = None,
    cp: int | None = None,
    user: int | None = None,
    tool: int | None = None,
) -> list[str]:
    """Build a list of V3-style DynParam strings from keyword arguments."""
    params: list[str] = []
    if speed_j is not None:
        params.append(f"SpeedJ={speed_j}")
    if speed_l is not None:
        params.append(f"SpeedL={speed_l}")
    if accel_j is not None:
        params.append(f"AccJ={accel_j}")
    if accel_l is not None:
        params.append(f"AccL={accel_l}")
    if speed is not None:
        params.append(f"SpeedJ={speed}")
    if accel is not None:
        params.append(f"AccJ={accel}")
    if cp is not None:
        params.append(f"CP={cp}")
    if user is not None:
        params.append(f"User={user}")
    if tool is not None:
        params.append(f"Tool={tool}")
    return params


class RelativeMotionV3(RelativeMotion):
    """Concrete RelativeMotion implementation for V3 API."""

    def rel_joint_mov_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        *,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative move with joint offsets."""
        dyn = _build_dyn_params(speed_j=speed, accel_j=accel)
        return self.native.move.rel_joint_mov_j(j1, j2, j3, j4, j5, j6, *dyn)

    def rel_mov_j_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        tool: int | None = None,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative joint move in tool coordinate system."""
        tool_val = tool if tool is not None else 0
        return self.native.move.rel_mov_j_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            tool_val,
        )

    def rel_mov_j_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative joint move in user coordinate system."""
        user_val = user if user is not None else 0
        dyn = _build_dyn_params(speed_j=speed, accel_j=accel)
        return self.native.move.rel_mov_j_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user_val,
            *dyn,
        )

    def rel_mov_l_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        tool: int | None = None,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative linear move in tool coordinate system."""
        tool_val = tool if tool is not None else 0
        return self.native.move.rel_mov_l_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            tool_val,
        )

    def rel_mov_l_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        *,
        user: int | None = None,
        speed: int | None = None,
        accel: int | None = None,
    ) -> int:
        """Relative linear move in user coordinate system."""
        user_val = user if user is not None else 0
        dyn = _build_dyn_params(speed_l=speed, accel_l=accel)
        return self.native.move.rel_mov_l_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user_val,
            *dyn,
        )
