from __future__ import annotations

"""Concrete namespace implementations for ts_dobot_api.

Auto-generated by scripts/generate_v3_v4_namespaces.py
"""


from typing import TYPE_CHECKING

from ..api_namespaces import (
    System,
)

if TYPE_CHECKING:
    from ..types import Pose


# ============================================================================
# V3 NAMESPACE IMPLEMENTATIONS
# ============================================================================


def _pose_from_tuple(t: tuple[float, ...]) -> Pose:
    """Convert a V3 Pose (plain tuple) to our unified Pose dataclass."""
    return Pose(x=t[0], y=t[1], z=t[2], rx=t[3], ry=t[4], rz=t[5])


def _build_dyn_params(
    *,
    speed_j: int | None = None,
    speed_l: int | None = None,
    accel_j: int | None = None,
    accel_l: int | None = None,
    speed: int | None = None,
    accel: int | None = None,
    cp: int | None = None,
    user: int | None = None,
    tool: int | None = None,
) -> list[str]:
    """Build a list of V3-style DynParam strings from keyword arguments."""
    params: list[str] = []
    if speed_j is not None:
        params.append(f"SpeedJ={speed_j}")
    if speed_l is not None:
        params.append(f"SpeedL={speed_l}")
    if accel_j is not None:
        params.append(f"AccJ={accel_j}")
    if accel_l is not None:
        params.append(f"AccL={accel_l}")
    if speed is not None:
        params.append(f"SpeedJ={speed}")
    if accel is not None:
        params.append(f"AccJ={accel}")
    if cp is not None:
        params.append(f"CP={cp}")
    if user is not None:
        params.append(f"User={user}")
    if tool is not None:
        params.append(f"Tool={tool}")
    return params


class SystemV3(System):
    """Concrete System implementation for V3 API."""

    def clear_error(self) -> None:
        """Clear controller error/alarm information."""
        self.native.clear_error()

    def disable_robot(self) -> None:
        """Disable the robot."""
        self.native.disable_robot()

    def emergency_stop(self) -> None:
        """Trigger an emergency stop."""
        self.native.emergency_stop()

    def enable_robot(
        self,
        load: float = 0.0,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
    ) -> None:
        """Enable the robot."""
        self.native.enable_robot(load=load, center_x=center_x, center_y=center_y, center_z=center_z)

    def pause_script(self) -> None:
        self.native.pause_script()

    def power_on(self) -> None:
        """Power on the robot."""
        self.native.power_on()

    def reset_robot(self) -> None:
        """Reset the robot controller."""
        self.native.reset_robot()

    def resume_script(self) -> None:
        self.native.resume_script()

    def run_script(self, project_name: str) -> None:
        self.native.run_script(project_name)

    def speed_factor(self, speed: int) -> None:
        """Set the global speed factor (1-100)."""
        self.native.speed_factor(speed)

    def stop_script(self) -> None:
        self.native.stop_script()


__all__ = [
    "ConfigV3",
    "ErrorHandlingV3",
    "FeedbackV3",
    "IoV3",
    "LifecycleV3",
    "ModbusV3",
    "MotionV3",
    "QueryV3",
    "RawV3",
    "RelativeMotionV3",
    "SystemV3",
]
